#!/usr/bin/env bash
# Build the WASM engine core and embed it as a base64 TS module, so the web
# build (Vite, GitHub Pages CI, vitest) needs no Rust toolchain and no asset
# path handling. Requires: rustup with the wasm32-unknown-unknown target.
set -euo pipefail
cd "$(dirname "$0")/engine-core"

RUSTFLAGS="-C target-feature=+simd128" cargo build --release --target wasm32-unknown-unknown

WASM=target/wasm32-unknown-unknown/release/engine_core.wasm
OUT=../../src/sim/wasm/engine-core-b64.ts

SIZE=$(stat -c%s "$WASM")
B64=$(base64 -w 0 "$WASM")
cat > "$OUT" <<EOF
// GENERATED by rust/build.sh — do not edit. Source: rust/engine-core/src/lib.rs
// wasm binary: ${SIZE} bytes, built $(date -u +%Y-%m-%d) with $(rustc --version | cut -d' ' -f1-2).
export const ENGINE_CORE_WASM_B64 =
  '${B64}';
EOF
echo "wrote $OUT ($(stat -c%s "$OUT") bytes)"
